name = "bypasser"
main = "index.js"
compatibility_date = "2025-09-13"
# account_id = "" # optional: your unique Cloudflare account ID

workers_dev = true
preview_urls = true

[[routes]]
pattern = "bypasser.andrewe.dev"
custom_domain = true

[assets]
directory = "./public"

[vars]
VERSION = "0.0.0"
EXPOSE_RULESET = "true"
RULESET_URL = "https://bypass.andrewe.dev/manifest.json"
ALLOWED_DOMAINS_RULESET = "true"

[triggers]
crons = ["0 12 * * *"]

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "20da3ef2e92642c49e05dbc37c64e334"
