name = "ladder"
main = "index.js"
compatibility_date = "2025-09-13"
# account_id = "" # optional: your unqiue Cloudflare account ID

workers_dev = true # use default {hostname}.{account}.workers.dev

# [[routes]]
# pattern = "ladder.example.com"
# custom_domain = true

# [build]
# command = "npm run build"

[assets]
directory = "./public"

# Environment variables for Ladder compatibility
# These can be set via Cloudflare dashboard or wrangler commands:
# wrangler secret put USERPASS
# wrangler env set USER_AGENT "custom agent"
[vars]
EXPOSE_RULESET = "true"
ALLOWED_DOMAINS_RULESET = "false"

# Optional vars (commented out - set via dashboard/CLI):
# USER_AGENT = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
# USERPASS = "username:password"
# ALLOWED_DOMAINS = "example.com,example.org"
# X_FORWARDED_FOR = "66.249.66.1"
# DISABLE_FORM = "false"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
