name = "ladder"
main = "index.js"
compatibility_date = "2025-09-13"
account_id = "" # your Cloudflare account ID

workers_dev = true # use default {hostname}.{account}.workers.dev

# [[routes]]
# pattern = "ladder.example.com"
# custom_domain = true

[assets]
directory = "./public"

[vars]
RULESET_URL = ""
	
[triggers]
# Auto-update rulesets every 4 hours
crons = ["0 */4 * * *"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
