#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import yaml from 'yaml';

const BPC_FILE = 'sites_aggregated.js';
const LADDER_FILE = 'ruleset-ladder.yaml';
const BPC_OUTPUT_FILE = 'ruleset-bpc-embedded.json';
const LADDER_OUTPUT_FILE = 'ruleset-ladder-embedded.json';
const LADDER_RUNTIME_MODULE = 'src/runtime/ladder-rules.generated.js';
const DEFAULT_OUTPUT_FILE = 'ruleset-embedded.json';

let bpcMapper = null;
async function loadBpcMapper() {
  if (bpcMapper) {
    return bpcMapper;
  }

  bpcMapper = await import('./bpc-mapper.mjs');
  return bpcMapper;
}

function loadLocalBPC() {
  const bpcPath = path.resolve(BPC_FILE);
  if (!fs.existsSync(bpcPath)) {
    throw new Error(`Missing local BPC file '${BPC_FILE}' (expected at ${bpcPath})`);
  }
  return fs.readFileSync(bpcPath, 'utf-8');
}

async function fetchText(url, label) {
  const response = await fetch(url, { cache: 'no-store' });
  if (!response.ok) {
    throw new Error(`Failed to fetch ${label} from ${url}: HTTP ${response.status}`);
  }
  return response.text();
}

function loadWranglerRulesetURL() {
  const wranglerPath = path.resolve('wrangler.toml');
  if (!fs.existsSync(wranglerPath)) {
    return '';
  }

  const raw = fs.readFileSync(wranglerPath, 'utf-8');
  const match = raw.match(/^\s*RULESET_URL\s*=\s*["']([^"']+)["']/m);
  return match?.[1] || '';
}

async function loadBPCSource() {
  const localFile = process.env.BPC_SOURCE_FILE;
  if (localFile) {
    const localPath = path.resolve(localFile);
    return {
      text: fs.readFileSync(localPath, 'utf-8'),
      source: localPath,
      version: null,
    };
  }

  if (process.env.BPC_SOURCE === 'local') {
    return {
      text: loadLocalBPC(),
      source: path.resolve(BPC_FILE),
      version: null,
    };
  }

  const manifestURL = process.env.BPC_MANIFEST_URL || process.env.RULESET_URL || loadWranglerRulesetURL();
  if (!manifestURL) {
    throw new Error(
      'Missing BPC manifest URL. Set BPC_MANIFEST_URL or RULESET_URL, or define RULESET_URL in wrangler.toml.',
    );
  }

  const manifestText = await fetchText(manifestURL, 'ruleset manifest');
  const manifest = JSON.parse(manifestText);
  const entry = manifest?.sites_aggregated_json || manifest?.sites_aggregated_js;

  if (!entry?.url || !entry?.version) {
    throw new Error(`Manifest ${manifestURL} is missing sites_aggregated_json/sites_aggregated_js url/version`);
  }

  return {
    text: await fetchText(entry.url, 'sites_aggregated ruleset'),
    source: entry.url,
    version: entry.version,
  };
}

function loadLadderRules() {
  const ladderPath = path.resolve(LADDER_FILE);
  if (!fs.existsSync(ladderPath)) {
    console.warn(`No Ladder YAML found at ${ladderPath}; continuing without Ladder overlays.`);
    return [];
  }

  const raw = fs.readFileSync(ladderPath, 'utf-8');
  const parsed = yaml.parse(raw);
  return Array.isArray(parsed) ? parsed : [];
}

function countDomains(rules) {
  let domainCount = 0;
  for (const rule of rules) {
    if (rule.domain) {
      domainCount += 1;
    }
    if (Array.isArray(rule.domains)) {
      domainCount += rule.domains.length;
    }
  }
  return domainCount;
}

async function main() {
  try {
    const mapper = await loadBpcMapper();

    const bpcSource = await loadBPCSource();
    const bpcText = bpcSource.text;
    const bpcData = mapper.parseSitesAggregatedText(bpcText);
    const versionSuffix = bpcSource.version ? ` version ${bpcSource.version}` : '';
    console.log(`Loaded ${bpcData.length} BPC entries from ${bpcSource.source}${versionSuffix}`);
    mapper.validateBPCData(bpcData);

    const ladderRules = loadLadderRules();
    fs.writeFileSync(LADDER_OUTPUT_FILE, JSON.stringify(ladderRules));
    fs.mkdirSync(path.dirname(LADDER_RUNTIME_MODULE), { recursive: true });
    fs.writeFileSync(
      LADDER_RUNTIME_MODULE,
      `// Auto-generated by scripts/build-rules.js\nexport default ${JSON.stringify(ladderRules)};\n`,
    );
    console.log(
      `Generated ${LADDER_OUTPUT_FILE} with ${ladderRules.length} Ladder rules covering ${countDomains(ladderRules)} domains`,
    );
    console.log(`Generated ${LADDER_RUNTIME_MODULE}`);

    const bpcOnlyRules = mapper.buildBpcOnlyRuleset(bpcData);
    fs.writeFileSync(BPC_OUTPUT_FILE, JSON.stringify(bpcOnlyRules));
    console.log(
      `Generated ${BPC_OUTPUT_FILE} with ${bpcOnlyRules.length} rules covering ${countDomains(bpcOnlyRules)} domains`,
    );

    const mergedRules = mapper.buildMergedRuleset(bpcData, ladderRules);
    fs.writeFileSync(DEFAULT_OUTPUT_FILE, JSON.stringify(mergedRules));
    console.log(
      `Generated ${DEFAULT_OUTPUT_FILE} with ${mergedRules.length} rules covering ${countDomains(mergedRules)} domains`,
    );
  } catch (error) {
    console.error('Error building ruleset:', error);
    process.exit(1);
  }
}

main();
